name: Deploy releases

on:
  push:
    tags:
      - 'v*'

env:
  MVN_ARGS: --batch-mode --errors --fail-fast --no-transfer-progress

jobs:
  default:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Package with Maven
        id: maven_package
        run: |
          mvn --batch-mode package -DskipTests
          cd ./target/
          echo "::set-output name=zip_name::$(echo recheck.cli-*-bin.zip)"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/${{ steps.maven_package.outputs.zip_name }}
          asset_name: ${{ steps.maven_package.outputs.zip_name }}
          asset_content_type: application/zip
